from __future__ import annotations

CANONICAL_COLUMNS: tuple[str, ...] = (
    "id",
    "nom_estab",
    "raz_social",
    "codigo_act",
    "nombre_act",
    "per_ocu",
    "tipo_vial",
    "nom_vial",
    "tipo_v_e_1",
    "nom_v_e_1",
    "tipo_v_e_2",
    "nom_v_e_2",
    "tipo_v_e_3",
    "nom_v_e_3",
    "numero_ext",
    "letra_ext",
    "edificio",
    "edificio_e",
    "numero_int",
    "letra_int",
    "tipo_asent",
    "nomb_asent",
    "tipocencom",
    "nom_cencom",
    "num_local",
    "cod_postal",
    "cve_ent",
    "entidad",
    "cve_mun",
    "municipio",
    "cve_loc",
    "localidad",
    "ageb",
    "manzana",
    "telefono",
    "correoelec",
    "www",
    "tipounieco",
    "latitud",
    "longitud",
    "fecha_alta",
    "clee",
    "snapshot_period",
    "source_file",
    "federation",
    "schema_version",
    "extraction_ts",
    "raw_extra_json",
)

REQUIRED_MINIMUM_COLUMNS: tuple[str, ...] = (
    "id",
    "nom_estab",
    "codigo_act",
    "cve_ent",
    "entidad",
)

COLUMN_ALIASES: dict[str, str] = {
    "codigodeactividad": "codigo_act",
    "codigo_act": "codigo_act",
    "nombre_de_la_actividad": "nombre_act",
    "nombreact": "nombre_act",
    "tipo_v_e1": "tipo_v_e_1",
    "nom_v_e1": "nom_v_e_1",
    "tipo_v_e2": "tipo_v_e_2",
    "nom_v_e2": "nom_v_e_2",
    "tipo_v_e3": "tipo_v_e_3",
    "nom_v_e3": "nom_v_e_3",
    "tipo_de_asentamiento_humano": "tipo_asent",
    "nombre_asentamiento_humano": "nomb_asent",
    "tipocencom": "tipocencom",
    "tipo_cencom": "tipocencom",
    "nom_cen_com": "nom_cencom",
    "nomcencom": "nom_cencom",
    "tipo_unidad_economica": "tipounieco",
    "tipounieco": "tipounieco",
    "correo_e": "correoelec",
    "correo_electronico": "correoelec",
    "cve_municipio": "cve_mun",
    "municipio_delegacion": "municipio",
    "codigo_postal": "cod_postal",
}
